/**
 * IconPicker.tsx - Shared icon-picker popover with an icon-set dropdown
 * (Material Design bundled; Font Awesome / Phosphor / Tabler lazy-loaded
 * from /harvest_assets/icon-sets/). Used by the entities-block header icon
 * and the per-entity icon override in EntitiesEditor.
 */

import { useEffect, useMemo, useState } from "react";
import { Icon, WidgetIcon } from "./Icon";
import { loadIconSetScript } from "./WidgetPreview";
import { getIconEntry } from "../iconResolve";
import { WIDGET_ICON_NAMES } from "../widgetIcons";

const PH_WEIGHTS = ["thin", "light", "bold", "fill", "duotone"] as const;

/** Icon sets offered by the picker dropdown. mdi is bundled; the rest are
    lazy assets generated by the widget build from the curated maps. The six
    Phosphor entries all draw from the one "ph" asset, split by weight
    suffix so each weight gets its own grid. */
export const ICON_SETS: { id: string; label: string; prefix: string; weight?: string }[] = [
  { id: "mdi", label: "Material Design", prefix: "mdi" },
  { id: "fa", label: "Font Awesome", prefix: "fa" },
  { id: "ph", label: "Phosphor Regular", prefix: "ph" },
  ...PH_WEIGHTS.map(w => ({
    id: `ph-${w}`,
    label: `Phosphor ${w.charAt(0).toUpperCase()}${w.slice(1)}`,
    prefix: "ph",
    weight: w,
  })),
  { id: "tabler", label: "Tabler", prefix: "tabler" },
];

/**
 * Return the Phosphor weight a shipped name belongs to, or undefined for
 * regular weight. A name only counts as a weight variant when stripping the
 * suffix yields another shipped icon: regular names can legitimately end in
 * a weight word (e.g. ph:traffic-light), and "traffic-light" is only the
 * Light variant if "ph:traffic" also exists.
 */
function phWeightOf(name: string, icons: Record<string, unknown>): string | undefined {
  for (const w of PH_WEIGHTS) {
    if (name.endsWith(`-${w}`) && icons[name.slice(0, -(w.length + 1))] !== undefined) {
      return w;
    }
  }
  return undefined;
}

/**
 * Eagerly load the icon-set assets referenced by the given entries and
 * return a counter that bumps as each set registers, so callers re-render
 * and rows showing the domain fallback upgrade to the set glyph (the same
 * behaviour as the live card). Entries may be icon names ("fa:bolt") or
 * icon-set ids ("ph-duotone").
 */
export function useIconSets(iconNames: Array<string | null | undefined>): number {
  const [tick, setTick] = useState(0);
  const key = iconNames.filter(Boolean).join("|");
  useEffect(() => {
    const prefixes = new Set<string>();
    for (const name of iconNames) {
      if (!name) continue;
      const sep = name.indexOf(":");
      const prefix = sep > 0 ? name.slice(0, sep) : iconSetAsset(name);
      if (prefix && prefix !== "mdi" && ICON_SETS.some(s => s.prefix === prefix)) prefixes.add(prefix);
    }
    let cancelled = false;
    for (const prefix of prefixes) {
      loadIconSetScript(prefix)
        .then(() => { if (!cancelled) setTick(t => t + 1); })
        .catch(() => {});
    }
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);
  return tick;
}

/**
 * Map an icon-set id ("fa", "ph-duotone") to the asset/prefix that backs it
 * ("fa", "ph"), for loadIconSetScript and getIconSet calls.
 */
export function iconSetAsset(setId: string | null | undefined): string | null {
  if (!setId || setId === "mdi") return null;
  return ICON_SETS.find(s => s.id === setId)?.prefix
    ?? (setId.includes("-") ? setId.slice(0, setId.indexOf("-")) : setId);
}

/**
 * Global icon-set dropdown (whole-widget / whole-theme granularity, not the
 * per-icon picker). Options come from ICON_SETS so future sets appear
 * automatically.
 *
 * Two modes:
 * - themeDefaultSetId provided (widget-level setting): the theme's own set
 *   (mdi when the theme declares none) is labelled " (Theme default)" and
 *   is the selection whenever value is null; picking it stores null so the
 *   widget keeps following the theme. Picking any other set stores an
 *   explicit override that survives theme changes.
 * - themeDefaultSetId omitted (editing a theme itself): an explicit
 *   "Material Design (default)" empty option maps to null.
 */
export function IconSetSelect({ value, onChange, disabled, ariaLabel, themeDefaultSetId, className }: {
  value: string | null;
  onChange: (setId: string | null) => void;
  disabled?: boolean;
  ariaLabel: string;
  themeDefaultSetId?: string | null;
  className?: string;
}) {
  if (themeDefaultSetId !== undefined) {
    const defId = themeDefaultSetId && ICON_SETS.some(s => s.id === themeDefaultSetId)
      ? themeDefaultSetId
      : "mdi";
    return (
      <select
        className={className ?? "input"}
        value={value ?? defId}
        onChange={ev => onChange(ev.target.value === defId ? null : ev.target.value)}
        disabled={disabled}
        aria-label={ariaLabel}
      >
        {ICON_SETS.map(s => (
          <option key={s.id} value={s.id}>
            {s.label}{s.id === defId ? " (Theme default)" : ""}
          </option>
        ))}
      </select>
    );
  }
  return (
    <select
      className={className ?? "input"}
      value={value ?? ""}
      onChange={ev => onChange(ev.target.value || null)}
      disabled={disabled}
      aria-label={ariaLabel}
    >
      <option value="">Material Design (default)</option>
      {ICON_SETS.filter(s => s.id !== "mdi").map(s => (
        <option key={s.id} value={s.id}>{s.label}</option>
      ))}
    </select>
  );
}

/**
 * Translate an mdi icon name to its curated equivalent in an icon set
 * (weight ids like "ph-duotone" apply a name suffix when the variant
 * exists). Returns null when the set is not loaded or has no equivalent.
 * Panel-side mirror of the widget's iconNameForSet().
 */
export function translateToSet(mdiName: string | null | undefined, setId: string): string | null {
  if (!mdiName || !mdiName.startsWith("mdi:")) return null;
  const entry = ICON_SETS.find(s => s.id === setId);
  const prefix = entry?.prefix ?? iconSetAsset(setId);
  if (!prefix || prefix === "mdi") return null;
  const set = window.HArvest?.getIconSet?.(prefix);
  if (!set) return null;
  const target = set.aliases[mdiName];
  if (!target) return null;
  if (entry?.weight) {
    const weighted = `${target}-${entry.weight}`;
    if (set.icons[weighted]) return weighted;
  }
  return set.icons[target] ? target : null;
}

/**
 * Reverse-translate a set icon name back to the mdi name it was curated
 * from, so switching sets can re-translate from the same base. Falls back
 * to the entity's default icon when the value is unset or unmappable.
 */
function mdiBaseFor(value: string | null | undefined, defaultIcon: string | null | undefined): string | null {
  if (!value) return defaultIcon ?? null;
  if (value.startsWith("mdi:")) return value;
  const sep = value.indexOf(":");
  const set = sep > 0 ? window.HArvest?.getIconSet?.(value.slice(0, sep)) : undefined;
  if (set) {
    let found = Object.keys(set.aliases).find(k => set.aliases[k] === value);
    if (!found) {
      const weight = phWeightOf(value, set.icons);
      if (weight) {
        const base = value.slice(0, -(weight.length + 1));
        found = Object.keys(set.aliases).find(k => set.aliases[k] === base);
      }
    }
    if (found) return found;
  }
  return defaultIcon ?? null;
}

interface IconPickerProps {
  /** Current icon key ("mdi:x", "fa:y", ...) or null for default. */
  value: string | null;
  /** Called with the picked icon key. */
  onPick: (icon: string) => void;
  /** Called when "Reset to default" is clicked; button hidden if omitted
      or value is null. */
  onClear?: () => void;
  disabled?: boolean;
  ariaLabel: string;
  /** Effective global icon set (widget icon_set ?? theme icon_set); the
      dropdown opens on this set when no per-entity value is set. */
  defaultSetId?: string | null;
  /** The entity's default (server-resolved) mdi icon; used as the
      translation base when switching sets. */
  defaultIcon?: string | null;
}

export function IconPicker({ value, onPick, onClear, disabled, ariaLabel, defaultSetId, defaultIcon }: IconPickerProps) {
  const [open, setOpen] = useState(false);
  const [filter, setFilter] = useState("");
  const [setId, setSetId] = useState("mdi");
  const [loadState, setLoadState] = useState<"ready" | "loading" | "error">("ready");
  const [, setTick] = useState(0);

  const fallbackSetId = defaultSetId && ICON_SETS.some(s => s.id === defaultSetId)
    ? defaultSetId
    : "mdi";

  // Follow the current value's set (and Phosphor weight) when opening; with
  // no per-entity value, open on the widget's effective global set.
  const openPicker = () => {
    let id = fallbackSetId;
    if (value) {
      const sep = value.indexOf(":");
      const prefix = sep > 0 ? value.slice(0, sep) : "mdi";
      id = ICON_SETS.find(s => s.prefix === prefix)?.id ?? "mdi";
      if (prefix === "ph") {
        const icons = window.HArvest?.getIconSet?.("ph")?.icons ?? {};
        const weight = phWeightOf(value, icons);
        if (weight) id = `ph-${weight}`;
      }
    }
    setSetId(id);
    setFilter("");
    setOpen(v => !v);
  };

  // Switching the set immediately applies the equivalent glyph for the
  // current icon (curated mapping, from the value's mdi base or the
  // entity's default icon), so the dropdown acts as a per-entity icon-set
  // switch as well as a grid filter. No equivalent = icon unchanged.
  const changeSet = (id: string) => {
    setSetId(id);
    setFilter("");
    const apply = async () => {
      const base = mdiBaseFor(value, defaultIcon);
      const entry = ICON_SETS.find(s => s.id === id);
      if (!entry || entry.prefix === "mdi") {
        if (!value) return; // already showing the default mdi icon
        if (base && base !== (defaultIcon ?? null)) onPick(base);
        else if (onClear) onClear();
        else if (base) onPick(base);
        return;
      }
      try {
        await loadIconSetScript(entry.prefix);
      } catch {
        return;
      }
      const translated = translateToSet(base, id);
      if (translated && translated !== value) onPick(translated);
    };
    void apply();
  };

  const setEntry = ICON_SETS.find(s => s.id === setId) ?? ICON_SETS[0];

  useEffect(() => {
    if (!open || setEntry.prefix === "mdi") {
      setLoadState("ready");
      return;
    }
    if (window.HArvest?.getIconSet?.(setEntry.prefix)) {
      setLoadState("ready");
      return;
    }
    let cancelled = false;
    setLoadState("loading");
    loadIconSetScript(setEntry.prefix)
      .then(() => { if (!cancelled) { setLoadState("ready"); setTick(t => t + 1); } })
      .catch(() => { if (!cancelled) setLoadState("error"); });
    return () => { cancelled = true; };
  }, [open, setEntry.prefix]);

  const names = useMemo(() => {
    if (setEntry.prefix === "mdi") return WIDGET_ICON_NAMES;
    const set = window.HArvest?.getIconSet?.(setEntry.prefix);
    if (!set) return [];
    let keys = Object.keys(set.icons);
    if (setEntry.prefix === "ph") {
      keys = keys.filter(n => phWeightOf(n, set.icons) === setEntry.weight);
    }
    return keys.sort();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [setId, loadState, open]);

  const lower = filter.toLowerCase();
  const shown = names.filter(n => !lower || n.slice(n.indexOf(":") + 1).includes(lower));

  return (
    <div style={{ position: "relative" }}>
      <button
        className="icon-picker-btn"
        title={value ? `Icon: ${value}` : "Pick icon"}
        disabled={disabled}
        onClick={openPicker}
        type="button"
        aria-label={ariaLabel}
        aria-expanded={open}
      >
        {value && getIconEntry(value) ? (
          <WidgetIcon name={value} size={16} />
        ) : (
          <Icon name="tune" size={14} />
        )}
      </button>
      {open && (
        <div className="icon-picker-popover" role="dialog" aria-label="Icon picker">
          <select
            className="input icon-picker-set"
            value={setId}
            onChange={ev => changeSet(ev.target.value)}
            aria-label="Icon set"
          >
            {ICON_SETS.map(s => (
              <option key={s.id} value={s.id}>{s.label}</option>
            ))}
          </select>
          <input
            className="input icon-picker-filter"
            type="text"
            aria-label="Filter icons"
            placeholder="Filter icons..."
            value={filter}
            onChange={ev => setFilter(ev.target.value)}
            autoFocus
          />
          {value && onClear && (
            <button
              className="icon-picker-clear"
              type="button"
              onClick={() => { setOpen(false); setFilter(""); setSetId(fallbackSetId); onClear(); }}
            >
              <Icon name="close" size={11} /> Reset to default
            </button>
          )}
          {loadState === "loading" && (
            <div className="icon-picker-status">Loading icon set...</div>
          )}
          {loadState === "error" && (
            <div className="icon-picker-status error">Failed to load icon set.</div>
          )}
          {loadState === "ready" && (
            <div className="icon-picker-grid" role="listbox" aria-label="Icons">
              {shown.map(iconKey => (
                <button
                  key={iconKey}
                  className={"icon-picker-tile" + (value === iconKey ? " selected" : "")}
                  type="button"
                  role="option"
                  aria-selected={value === iconKey}
                  title={iconKey}
                  onClick={() => { setOpen(false); setFilter(""); onPick(iconKey); }}
                >
                  <WidgetIcon name={iconKey} size={18} />
                </button>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
