title: HArvest Documentation
description: HArvest - Live Home Assistant widgets on any webpage
baseurl: "/harvest"
url: "https://sfox38.github.io"
include:
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.png"
  - "*.jpg"
exclude:
  - Gemfile
  - Gemfile.lock
